name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker image
        env:
          DOCKER_REGISTRY: registry.digitalocean.com/<your-registry-name>
        run: |
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u <your-docker-username> --password-stdin $DOCKER_REGISTRY
          docker buildx build --push --tag $DOCKER_REGISTRY/<your-image-name>:<version> .
