name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker image
        env:
          DOCKER_REGISTRY: registry.digitalocean.com/petshop123
        run: |
         docker login -u dop_v1_423f2a21a56ab33dc773f6571011db472289a99bf14a487e80bc5c5c4f5a6d17 --password dop_v1_423f2a21a56ab33dc773f6571011db472289a99bf14a487e80bc5c5c4f5a6d17
          docker buildx build --push --tag $DOCKER_REGISTRY/backend:latest .
